services:
  first:
    build: ./FirstMicroservice
    container_name: first
    ports:
      - "9031:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app_network

  second:
    build: ./SecondMicroservice
    container_name: second
    ports:
      - "8100:8100"
    environment:
      - UVICORN_RELOAD=true
    depends_on:
      - postgresql
    networks:
      - app_network

  postgresql:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      app_network:
        aliases:
          - dbhost

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8000:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql
    networks:
      - app_network

volumes:
  pgdata:
  pgadmin:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16